spring:
  application:
    name: config-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xtawgipl/springCloudDemo.git
          search-paths: /configDemo/src/main/resources/config/
#          username:
#          password:
# 查看配置 http://localhost:8080/config/dev/master
server:
  port: 8080
# 查看监控信息 http://localhost:9091/actuator
management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: '*'
    shutdown:
      enabled: true
    restart:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true